apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: {{ include "dify.fullname" . }}-api-storage
  labels:
    app: api-storage
  {{- include "dify.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.api.storageRequest | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: {{ include "dify.fullname" . }}-worker-storage
  labels:
    app: worker-storage
  {{- include "dify.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.worker.storageRequest | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: {{ include "dify.fullname" . }}-db-storage
  labels:
    app: db-storage
  {{- include "dify.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.db.storageRequest | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: {{ include "dify.fullname" . }}-plugin-daemon-storage
  labels:
    app: plugin-daemon-storage
  {{- include "dify.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.pluginDaemon.storageRequest | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: {{ include "dify.fullname" . }}-redis-storage
  labels:
    app: redis-storage
  {{- include "dify.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.redis.storageRequest | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: {{ include "dify.fullname" . }}-weaviate-storage
  labels:
    app: weaviate-storage
  {{- include "dify.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.weaviate.storageRequest | quote }}